config/routes.rb
Rails.application.routes.draw do
  resources :uptimes
  get 'mission_records/index'
  get 'polygon/polygon'
  get 'welcome/index'
  get 'forecasts/show'
  get 'forecasts/details'
  get 'forecasts/http'
  get 'drone/weather_check' => "drone#weather_check"
  put 'base/open_door'
  put 'base/close_door'

  resources :missions do
    collection do
      get :search
    end
  end
  resources :locations
  resources :comments
  resources :posts
  resources :nav_logs


  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :nav_logs
      get 'last_navlog', to: '/api/v1/nav_logs#last_navlog'
      resources :users
      resources :drone
      patch 'mission_status_change', to: 'drone#mission_status_change'
      patch 'terminate_mission', to: 'drone#terminate_mission'
      resources :missions
      get 'users_mission', to: 'missions#users_mission'
      get 'users_mission_last', to: 'missions#users_mission_last'
      get 'ongoing_mission', to: 'missions#ongoing_mission'
      post 'emergency_mission_sim', to: 'drone#emergency_mission_sim'
      post 'execute_emergency_mission', to: 'drone#execute_emergency_mission'

      resources :drone_availables
      post 'available', to: 'drone_availables#available'
    end
  end

  post 'polygon/send_coordinates' => 'polygon#get_coordinates'

  post '/auth/login', to: 'api/v1/authentication#login'



  get 'index/index'
  get 'index/about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/drone" => 'drone#index'
  get 'drone/drone_registration'
  get 'drone/drone_list' => "drone#drone_list"
  get 'drone/users_list'
  get 'drone/users_mission'
  get 'drone/drone_tracker'
  get 'drone/drone_mission'

  get 'drone/done'
  # get 'drone/drone_tracker' => 'drone#check_status'
  put 'drone/status_change'

  get 'drone/drone_tracker' => 'drone#check_status'
  put 'drone/terminate_mission'
  get 'drone/release_servo'
  get 'drone/lock_servo'

  put 'drone/mission_status_change'
  put 'drone/check_status'
  get 'drone/check_status'
  get '/drone/nav_logs_json' => 'drone#nav_logs_json'
  post 'drone/drone_create'
  put 'drone/ban_user'
  get 'drone/:id/drone_edit' => 'drone#drone_edit', :as => :drone_drone_edit

  patch 'drone/:id/drone_edit' => 'drone#drone_update'
  put 'drone/:id'=> 'drone#drone_update'

  devise_scope :user do
    authenticated :user do
      root to: 'index#index'
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end

  end

  # root 'index#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/drone.rb
class Drone < ApplicationRecord
  belongs_to :user
  has_many :nav_logs
  has_many :missions

end

app/models/drone_available.rb
class DroneAvailable < ApplicationRecord

end

app/models/forecast.rb
class Forecast < ApplicationRecord

  def get_weather_data
    ForecastIO.forecast(14.0754804, 100.6100677, params: { exclude: 'minutely, hourly'})
  end

end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :drone
  belongs_to :location
  belongs_to :user
  has_many :uptimes
  after_update :save_endtime

  def save_endtime

      @finduptime = Uptime.last
      @finduptime.end_time = Time.now
      @finduptime.save

  end

  def self.search(params)
    missions = Mission.where("Location LIKE ? or Name LIKE ?", "%{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
    missions
  end



end

app/models/nav_log.rb
class NavLog < ApplicationRecord
  belongs_to :drone
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/status_log.rb
class StatusLog < ApplicationRecord
  belongs_to :drone
end

app/models/uptime.rb
class Uptime < ApplicationRecord
  belongs_to :mission


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  has_many :missions

end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/drone_helper.rb
module DroneHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/polygon_helper.rb
module PolygonHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/uptimes_helper.rb
module UptimesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/index/about.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

<!--<p id="notice"><%#= notice %></p>-->
<style>
  /* Make the image fully responsive */
  .carousel-inner img {
    width: 100%;
    height: 70%;
  }
</style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">DroneTracker</a>
    </div>
    <ul class="nav navbar-nav">
      <div class="container">
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Drone
          </button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="/drone/drone_list">Drone List</a>
            <a class="dropdown-item" href="/drone/drone_registration">Register a Drone</a>
          </div>
        </div>
        <a href="/missions" class="btn btn-primary" role="button">Mission List</a>
        <a href="/" class="btn btn-info" role="button">Home</a>
        <a href="https://validator.w3.org" class="btn btn-info" role="button">Validate this Site</a>
        <a href="/posts" class="btn btn-info" role="button">Forum</a>
        <% if user_signed_in? %>
          <% if current_user.admin %>
            <a href="/drone/users_lists" class="btn btn-info" role="button">User Management</a>
          <% end %>

          </div>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <div class="container">



              <li><p class="navbar-text">Signed in as <%= current_user.email %></p></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <% end %>

        </div>
        </ul>
        </div>
</nav>

<div id="demo" class="carousel slide" data-ride="carousel">
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <a href="/drone/drone_list"><img src="https://d2v9y0dukr6mq2.cloudfront.net/video/thumbnail/NrM0QFs3gilniuv44/3d-model-of-a-flying-drone-on-a-dark-background-4k-video_bjff7lyvdg_thumbnail-full05.png" alt="Los Angeles" width="1100" height="500">
        <div class="carousel-caption">
          <h3>Drone List</h3>
          <p>We'd love to view some drones.</p>
        </div>
      </a>
    </div>
    <div class="carousel-item">
      <a href="/missions"><img src="https://s3.amazonaws.com/giveffect-assets/blog/wp-content/uploads/2018/04/03132106/How-to-Craft-the-Best-Mission-Statement-for-Your-Business-1068x601.jpg" alt="Chicago" width="1100" height="500">
        <div class="carousel-caption">
          <h3>Mission List</h3>
          <p>Let's create some missions.</p>
        </div>
      </a>
    </div>
    <div class="carousel-item">
      <a href="/posts"> <img src="https://www.marketingdonut.co.uk/sites/default/files/questions-that-research-could-help-you-answer-366899399.jpg" alt="New York" width="1100" height="500">
        <div class="carousel-caption">
          <h3>Forum</h3>
          <p>Ask me anything</p>
        </div>
      </a>
    </div>
  </div>
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>
<hr>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1>Web App For Drone</h1>
    <p>Presented by Wai Yan Aung(Drone Team).</p>
  </div>
</div>

<div class="container">
  <p>This is the web app for drone delivery, currently you can create mission, register drone and post in the forum. </p>
  <p>Goal: Delivering mail with drone from one place to another using this web app.</p>
  <p>Upcoming features: Test with real drone after calibration.</p>
</div>
</body>


</div>

<!--<br>-->

<%#= link_to 'New Drone', new_drone_path %>

app/views/index/index.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

<!--<p id="notice"><%#= notice %></p>-->
<style>
  /* Make the image fully responsive */
  .carousel-inner img {
    width: 100%;
    height: 70%;
  }

  .container1 {
    padding: 10px;
  }

  .led {
    color: #777;
    font-weight: normal;
    float: left;
  }

  .available {
    float: right;
    margin-right: 15px;
  }

  .not_available {
    float: right;
    margin-right: 15px;
  }

  .led-green {
    /*margin: 0 auto;*/
    width: 10px;
    height: 10px;
    background-color: #80ff00;
    border-radius: 50%;
    box-shadow: rgba(0, 0, 0, 0.2) 0 -1px 7px 1px, inset #304701 0 -1px 9px, #89FF00 0 2px 12px;
    display: inline-block;
  }

  .led-red {
    /*margin: 0 auto;*/
    width: 10px;
    height: 10px;
    background-color: #ff0000;
    border-radius: 50%;
    box-shadow: rgba(0, 0, 0, 0.2) 0 -1px 7px 1px, inset #ff0000 0 -1px 9px, rgba(255, 0, 0, 0.5) 0 2px 12px;
    display: inline-block;
  }

  #customers {
    /*font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;*/
    border-collapse: collapse;
    width: 100%;
    margin-bottom: 10px;
  }

  #customers td, #customers th {
    border: 1px solid #ddd;
    padding: 8px;
  }

  #customers tr:nth-child(even){background-color: #f2f2f2;}

  #customers tr:hover {background-color: #ddd;}

  #customers th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: left;
    background-color: #4CAF50;
    color: white;
  }

</style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">DroneTracker</a>
    </div>
    <ul class="nav navbar-nav">
      <div class="container">
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Drone
          </button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="/drone/drone_list">Drone List</a>
            <a class="dropdown-item" href="/drone/drone_registration">Register a Drone</a>
          </div>
        </div>
        <a href="/missions" class="btn btn-primary" role="button">Mission List</a>



        <div class="btn btn-read">
          <%= link_to 'Field Observation Mission', welcome_index_path %>
        </div>



        <a href="/" class="btn btn-info" role="button">Home</a>
        <a href="https://validator.w3.org" class="btn btn-info" role="button">Validate this Site</a>
        <a href="/posts" class="btn btn-info" role="button">Forum</a>
        <a href="/forecasts/show" class="btn btn-info" role="button">Weather Forecast</a>

        <% if user_signed_in? %>
          <% if current_user.admin %>
            <a href="/drone/users_list" class="btn btn-info" role="button">User Management</a>
          <% end %>

          </div>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <div class="container">



              <li><p class="navbar-text">Signed in as <%= current_user.email %></p></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <% end %>

        </div>
        </ul>
  </div>
</nav>

<div id="demo" class="carousel slide" data-ride="carousel">
  <ul class="carousel-indicators">
    <li data-target="#demo" data-slide-to="0" class="active"></li>
    <li data-target="#demo" data-slide-to="1"></li>
    <li data-target="#demo" data-slide-to="2"></li>
  </ul>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <a href="/drone/drone_list"><img src="https://d2v9y0dukr6mq2.cloudfront.net/video/thumbnail/NrM0QFs3gilniuv44/3d-model-of-a-flying-drone-on-a-dark-background-4k-video_bjff7lyvdg_thumbnail-full05.png" alt="Los Angeles" width="1100" height="500">
        <div class="carousel-caption">
          <h3>Drone List</h3>
          <p>We'd love to view some drones.</p>
        </div>
      </a>
    </div>
    <div class="carousel-item">
      <a href="/missions"><img src="https://s3.amazonaws.com/giveffect-assets/blog/wp-content/uploads/2018/04/03132106/How-to-Craft-the-Best-Mission-Statement-for-Your-Business-1068x601.jpg" alt="Chicago" width="1100" height="500">
        <div class="carousel-caption">
          <h3>Mission List</h3>
          <p>Let's create some missions.</p>
        </div>
      </a>
    </div>
    <div class="carousel-item">
      <a href="/posts"> <img src="https://www.marketingdonut.co.uk/sites/default/files/questions-that-research-could-help-you-answer-366899399.jpg" alt="New York" width="1100" height="500">
        <div class="carousel-caption">
          <h3>Forum</h3>
          <p>Ask me anything</p>
        </div>
      </a>
    </div>
  </div>
  <a class="carousel-control-prev" href="#demo" data-slide="prev">
    <span class="carousel-control-prev-icon"></span>
  </a>
  <a class="carousel-control-next" href="#demo" data-slide="next">
    <span class="carousel-control-next-icon"></span>
  </a>
</div>

<div class="container1">
  <hr>
<h1>Available Drones</h1>
<span class="led">
      <span class="available">
         <span class="led-green"></span> : available
      </span>
      <span class="not_available">
        <span class="led-red"></span> :  not available
      </span>
    </span>
<br>
<br>
<table id="customers">
  <tr>
    <th>Drone ID and status</th>
    <th>Battery</th>
  </tr>
  <tr>
    <td><span class="led-red"></span> Drone1 </td>
    <td><%= @sim_battery %></td>
  </tr>
  <tr>
    <td><span class="led-red"></span> Drone2 </td>
    <td><%= @real_battery %></td>
  </tr>
  <tr>
    <td><span class="led-red"></span> Drone3 </td>
    <td><%= @real_battery %></td>
  </tr>
</table>
  <hr>
</div>

<div class="container">
<div class="row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <strong class="card-title">Drone Overview</strong>
        <hr>
        <h4 class="card-text">Total Drones: <%= @drone_count%></h4>
        <h4 class="card-text">Last Created Drone Name: <%= @last_drone.blank? ? "Not Available" : @last_drone%></h4>
        <h4 class="card-text">Status: <%= @last_status.blank? ? "Not Available" : @last_status%></h4>
        <h4 class="card-text">Last known Location: Latitude :<%= @last_latitude.blank? ? "Not Available" : @last_latitude %> & Longitude: <%= @last_longitude.blank? ? "Not Available" : @last_longitude  %></h4>
        <%= link_to 'Track this drone', drone_drone_tracker_path(drone: Drone.last), class: "btn btn-primary" %>

      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <strong class="card-title">Mission Overview</strong>
        <hr>
        <h4 class="card-text">Total Missions: <%= @mission_count%></h4>
        <h4 class="card-text">Last Created Mission Name: <%= @last_mission.blank? ? "Not Available" : @last_mission%></h4>
        <h4 class="card-text">Last Created Mission Destined Location: <%= @last_location.blank? ? "Not Available" : @last_location%></h4>
        <a href="/missions" class="btn btn-primary">Show all mission</a>
      </div>
    </div>
  </div>
</div>
</div>

<!-- Footer -->
<!-- Footer -->
<footer class="page-footer font-small indigo">

  <!-- Footer Links -->
  <div class="container">

    <!-- Grid row-->
    <div class="row text-center d-flex justify-content-center pt-5 mb-3">

      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="/index/about">About</a>
        </h6>
      </div>
      <!-- Grid column -->


      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="#!">Help</a>
        </h6>
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 mb-3">
        <h6 class="text-uppercase font-weight-bold">
          <a href="https://www.facebook.com/waiyan.aung.1884">Contact</a>
        </h6>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->
    <hr class="rgba-white-light" style="margin: 0 15%;">

    <!-- Grid row-->
    <div class="row d-flex text-center justify-content-center mb-md-0 mb-4">

      <!-- Grid column -->
      <div class="col-md-8 col-12 mt-5">
        <p style="line-height: 1.7rem">This is the final capstone project for Wai Yan Aung@DroneTeam.</p>
        <p style="line-height: 1.7rem"><h4>GITHUB REPO:https://github.com/williamsaung/drone</h4></p>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->
    <hr class="clearfix d-md-none rgba-white-light" style="margin: 10% 15% 5%;">

    <!-- Grid row-->
    <div class="row pb-3">
    </div>
  </div>
  </div>
  </div>

  <div class="footer-copyright text-center py-3">© 2019 Copyright:
    <a href="https://teamdronex.com"> teamdronex.com</a> (last_updated:4/1)
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
<!-- Footer -->
</body>


</div>

<!--<br>-->

<%#= link_to 'New Drone', new_drone_path %>