config/routes.rb
Rails.application.routes.draw do
  resources :uptimes
  get 'mission_records/index'
  get 'polygon/polygon'
  get 'welcome/index'
  get 'forecasts/show'
  get 'forecasts/details'
  get 'forecasts/http'
  get 'drone/weather_check' => "drone#weather_check"
  put 'base/open_door'
  put 'base/close_door'

  resources :missions do
    collection do
      get :search
    end
  end
  resources :locations
  resources :comments
  resources :posts
  resources :nav_logs


  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :nav_logs
      get 'last_navlog', to: '/api/v1/nav_logs#last_navlog'
      resources :users
      resources :drone
      patch 'mission_status_change', to: 'drone#mission_status_change'
      patch 'terminate_mission', to: 'drone#terminate_mission'
      resources :missions
      get 'users_mission', to: 'missions#users_mission'
      get 'users_mission_last', to: 'missions#users_mission_last'
      get 'ongoing_mission', to: 'missions#ongoing_mission'
      post 'emergency_mission_sim', to: 'drone#emergency_mission_sim'
      post 'execute_emergency_mission', to: 'drone#execute_emergency_mission'

      resources :drone_availables
      post 'available', to: 'drone_availables#available'
    end
  end

  post 'polygon/send_coordinates' => 'polygon#get_coordinates'

  post '/auth/login', to: 'api/v1/authentication#login'



  get 'index/index'
  get 'index/about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/drone" => 'drone#index'
  get 'drone/drone_registration'
  get 'drone/drone_list' => "drone#drone_list"
  get 'drone/users_list'
  get 'drone/users_mission'
  get 'drone/drone_tracker'
  get 'drone/drone_mission'

  get 'drone/done'
  # get 'drone/drone_tracker' => 'drone#check_status'
  put 'drone/status_change'

  get 'drone/drone_tracker' => 'drone#check_status'
  put 'drone/terminate_mission'
  get 'drone/release_servo'
  get 'drone/lock_servo'

  put 'drone/mission_status_change'
  put 'drone/check_status'
  get 'drone/check_status'
  get '/drone/nav_logs_json' => 'drone#nav_logs_json'
  post 'drone/drone_create'
  put 'drone/ban_user'
  get 'drone/:id/drone_edit' => 'drone#drone_edit', :as => :drone_drone_edit

  patch 'drone/:id/drone_edit' => 'drone#drone_update'
  put 'drone/:id'=> 'drone#drone_update'

  devise_scope :user do
    authenticated :user do
      root to: 'index#index'
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end

  end

  # root 'index#index'
end

app/models/drone.rb
class Drone < ApplicationRecord
  belongs_to :user
  has_many :nav_logs
  has_many :missions

end

app/controllers/api/v1/drone_controller.rb
module Api
  module V1
    class DroneController < ApplicationController
      before_action :authorize_request, except: :update
      # before_action :find_user, except: %i[create index]
      protect_from_forgery with: :null_session
      respond_to :json

      def index
        @drone= Drone.find(params[:id])
        respond_with @drone
      end

      def update
        @drone= Drone.find(params[:id])
        @drone.update(drone_params)
      end

      def terminate_mission
        @mission = Mission.find(params[:id])
        @drone = Drone.find(@mission.drone.id)
        @drone.status = params[:drone_status]
        @drone.save
        @mission.status = params[:mission_status]
        @mission.save

        if @drone.simulator?
          child_pid = spawn({"PATH" => "/home/ubuntu/.pyenv/shims:/home/ubuntu/.pyenv/bin:/home/ubuntu/.rbenv/plugins/ruby-build/bin:/home/ubuntu/.rbenv/shims:/home/ubuntu/.rbenv/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/.local/bin"}, "python ~/drone-comms/drone/thrift/rtl.py")
          # child_pid = spawn({"PATH" => "/home/ubuntu/.pyenv/shims:/home/ubuntu/.pyenv/bin:/home/ubuntu/.rbenv/plugins/ruby-build/bin:/home/ubuntu/.rbenv/shims:/home/ubuntu/.rbenv/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/.local/bin"}, "python ~/drone-comms/drone/mission.py #{connection_string} #{gps_latitude} #{gps_longitude} #{@mission.id} --drone_id #{@drone.id}")
          # child_pid = spawn({"PATH" => "/home/adam/.pyenv/shims:/home/adam/.pyenv/bin:/home/adam/.rbenv/plugins/ruby-build/bin:/home/adam/.rbenv/shims:/home/adam/.rbenv/bin:/home/adam/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/adam/.local/bin"}, "python ~/drone/drone-comms/drone/mission.py #{connection_string} #{gps_latitude} #{gps_longitude} #{@mission.id} --drone_id #{@drone.id}")
          Process.detach(child_pid)
        else
          child_pid = spawn({"PATH" => "/home/ubuntu/.pyenv/shims:/home/ubuntu/.pyenv/bin:/home/ubuntu/.rbenv/plugins/ruby-build/bin:/home/ubuntu/.rbenv/shims:/home/ubuntu/.rbenv/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/.local/bin"}, "python ~/drone-comms/drone/thrift/rtl.py --port 9091")
          # child_pid = spawn({"PATH" => "/home/ubuntu/.pyenv/shims:/home/ubuntu/.pyenv/bin:/home/ubuntu/.rbenv/plugins/ruby-build/bin:/home/ubuntu/.rbenv/shims:/home/ubuntu/.rbenv/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/.local/bin"}, "python ~/drone-comms/drone/mission.py #{connection_string} #{gps_latitude} #{gps_longitude} #{@mission.id} --drone_id #{@drone.id}")
          # child_pid = spawn({"PATH" => "/home/adam/.pyenv/shims:/home/adam/.pyenv/bin:/home/adam/.rbenv/plugins/ruby-build/bin:/home/adam/.rbenv/shims:/home/adam/.rbenv/bin:/home/adam/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/adam/.local/bin"}, "python ~/drone/drone-comms/drone/mission.py #{connection_string} #{gps_latitude} #{gps_longitude} #{@mission.id} --drone_id #{@drone.id}")
          Process.detach(child_pid)
        end
      end

      def mission_status_change

        @mission = Mission.find(params[:id])
        gps_latitude = @mission.location.latitude
        gps_longitude = @mission.location.longitude

        @drone = Drone.find(@mission.drone.id)
        @drone.status = params[:drone_status]
        @drone.save

        @mission.status = params[:mission_status]
        @mission.save

        connection_string = @drone.connection_string
        puts "Executing command 'python ~/drone-comms/drone/mission.py #{connection_string} #{gps_latitude} #{gps_longitude}'"

        # For simulators
        if @drone.simulator?
          child_pid = spawn({"PATH" => "/home/ubuntu/.pyenv/shims:/home/ubuntu/.pyenv/bin:/home/ubuntu/.rbenv/plugins/ruby-build/bin:/home/ubuntu/.rbenv/shims:/home/ubuntu/.rbenv/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/.local/bin"}, "python ~/drone-comms/drone/thrift/delivery.py #{gps_latitude} #{gps_longitude} 20 #{@mission.id} --drone_id #{@drone.id}")
          # child_pid = spawn({"PATH" => "/home/adam/.pyenv/shims:/home/adam/.pyenv/bin:/home/adam/.rbenv/plugins/ruby-build/bin:/home/adam/.rbenv/shims:/home/adam/.rbenv/bin:/home/adam/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/adam/.local/bin"}, "python ~/drone/drone-comms/drone/mission.py #{connection_string} #{gps_latitude} #{gps_longitude} #{@mission.id} --drone_id #{@drone.id}")
          Process.detach(child_pid)
        else
          child_pid = spawn({"PATH" => "/home/ubuntu/.pyenv/shims:/home/ubuntu/.pyenv/bin:/home/ubuntu/.rbenv/plugins/ruby-build/bin:/home/ubuntu/.rbenv/shims:/home/ubuntu/.rbenv/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/.local/bin"}, "python ~/drone-comms/drone/thrift/delivery.py #{gps_latitude} #{gps_longitude} 20 #{@mission.id} --drone_id #{@drone.id} --port 9091")
          # child_pid = spawn({"PATH" => "/home/adam/.pyenv/shims:/home/adam/.pyenv/bin:/home/adam/.rbenv/plugins/ruby-build/bin:/home/adam/.rbenv/shims:/home/adam/.rbenv/bin:/home/adam/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/adam/.local/bin"}, "python ~/drone/drone-comms/drone/mission.py #{connection_string} #{gps_latitude} #{gps_longitude} #{@mission.id} --drone_id #{@drone.id}")
          Process.detach(child_pid)
        end
        end


      def emergency_mission_sim
        @location = Location.create(:name => "Emergency", :latitude => params[:latitude], :longitude => params[:longitude])
        @drone = Drone.find(1) # sim
        if @drone.status == "Busy"
          puts "Drone is Busy"
        else
        @mission = Mission.create(:name => "Emergency", :weight => 25, :status => "Ongoing", :user_id => 1, :mission_type => "Emergency", :location_id => @location.id, :drone_id => @drone.id)
        child_pid = spawn({"PATH" => "/home/ubuntu/.pyenv/shims:/home/ubuntu/.pyenv/bin:/home/ubuntu/.rbenv/plugins/ruby-build/bin:/home/ubuntu/.rbenv/shims:/home/ubuntu/.rbenv/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/.local/bin"}, "python ~/drone-comms/drone/thrift/delivery.py #{params[:latitude]} #{params[:longitude]} 20 #{@mission.id} --drone_id #{@drone.id}")
        # child_pid = spawn({"PATH" => "/home/adam/.pyenv/shims:/home/adam/.pyenv/bin:/home/adam/.rbenv/plugins/ruby-build/bin:/home/adam/.rbenv/shims:/home/adam/.rbenv/bin:/home/adam/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/adam/.local/bin"}, "python ~/drone/drone-comms/drone/mission.py #{connection_string} #{gps_latitude} #{gps_longitude} #{@mission.id} --drone_id #{@drone.id}")
        Process.detach(child_pid)
        @drone.update(:status => "Busy")
        end
        end

      def execute_emergency_mission
        @location = Location.create(:name => "Emergency", :latitude => params[:latitude], :longitude => params[:longitude])
        @drone = Drone.find(2) # real
        if @drone.status == "Busy"
          puts "Drone is Busy"
        else
        @mission = Mission.create(:name => "Emergency", :weight => 25, :status => "Ongoing", :user_id => 1, :mission_type => "Emergency", :location_id => @location.id, :drone_id => @drone.id)
        child_pid = spawn({"PATH" => "/home/ubuntu/.pyenv/shims:/home/ubuntu/.pyenv/bin:/home/ubuntu/.rbenv/plugins/ruby-build/bin:/home/ubuntu/.rbenv/shims:/home/ubuntu/.rbenv/bin:/home/ubuntu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/.local/bin"}, "python ~/drone-comms/drone/thrift/delivery.py #{params[:latitude]} #{params[:longitude]} 20 #{@mission.id} --drone_id #{@drone.id} --port 9091 --base_port 8081")
        # child_pid = spawn({"PATH" => "/home/adam/.pyenv/shims:/home/adam/.pyenv/bin:/home/adam/.rbenv/plugins/ruby-build/bin:/home/adam/.rbenv/shims:/home/adam/.rbenv/bin:/home/adam/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/adam/.local/bin"}, "python ~/drone/drone-comms/drone/mission.py #{connection_string} #{gps_latitude} #{gps_longitude} #{@mission.id} --drone_id #{@drone.id}")
        Process.detach(child_pid)

        @drone.update(:status => "Busy")
        end
      end

      def drone_params
        params.permit(:status)
      end
    end
  end
end

app/helpers/drone_helper.rb
module DroneHelper
end

app/views/drone/drone_list.html.erb
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

</head>



<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">DroneTracker</a>
    </div>
    <ul class="nav navbar-nav">
      <div class="container">
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Drone
          </button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="/drone/drone_list">Drone List</a>
            <a class="dropdown-item" href="/drone/drone_registration">Register a Drone</a>
          </div>
        </div>
        <a href="/missions" class="btn btn-primary" role="button">Mission List</a>
        <a href="/" class="btn btn-info" role="button">Home</a>
        <a href="https://validator.w3.org" class="btn btn-info" role="button">Validate this Site</a>
        <a href="/posts" class="btn btn-info" role="button">Forum</a>
        <% if user_signed_in? %>
          <% if current_user.admin %>
            <a href="/drone/users_list" class="btn btn-info" role="button">User Management</a>
          <% end %>

          </div>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <div class="container">



              <li><p class="navbar-text">Signed in as <%= current_user.email %></p></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <% end %>
        </div>
        </ul>
  </div>
</nav>

<div class="col justify-content-start">
  <div class="row">
<div class="container">
  <h1>Drones</h1>
</div>
  </div>

<div class="row">
<div class="container">


  <div class="row">
    <% @drones.each do |drone| %>
    <div class="col-sm-4">

      <div class="card bg-light mt-5">

        <div class="card-body">
          <h4 class="card-title">Name: <%= drone.name %> </h4>
          <p class="font-weight-bold"> Status: <%= drone.status %> </p>
          <p>Drone ID: <%= drone.id %></p>
          <p>Connection String: <%= drone.connection_string %></p>
          <p>Description: <%= drone.description %></p>
          <p><%= link_to 'Edit', drone_drone_edit_path(drone), class: "btn btn-primary" %></p>
        </div>
        <ul class="list-group list-group-flush">
        </ul>
        <div class="card-body">
        <%= link_to 'Tracking', drone_drone_tracker_path(drone: drone.id), class: "btn btn-primary" %> <%= link_to "Create Mission", drone_drone_mission_path(drone_id: drone.id, user_id: current_user.id), class: "btn btn-primary" %>
        </div>
      </div>

    </div>

<%end %>

  </div>

</div>
</div>
</div>

</div>
</div>

<div class="container">

  <%= link_to 'Mission List', missions_path %>
</div>

<!--<br>-->

<%#= link_to 'New Drone', new_drone_path %>

app/views/drone/drone_mission.html.erb
<%= form_with(model: @mission, local: true) do |form| %>
  <% if @mission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mission.errors.count, "error") %> prohibited this mission from being saved:</h2>

      <ul>
        <% @mission.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">


  <div class="field">
    <%= form.label :Item_Name, class:'control-label' %>
    <input type="text" class="form-control" id="mission_name" placeholder="Item name" name="mission[name]">
    <%#= form.label :item_name %>
    <%#= form.text_field :name %>
  </div>


<hr>
    <div class="form-group ">
      <%= form.label :Location, class:'control-label' %>
      <%= collection_select( :mission, :location_id, Location.all, :id, :name,{include_blank: false}, {class: 'form-control '})%></div>


<!--  <div class="field">-->
    <%#= form.label :location %>
    <%#= collection_select( :mission, :location_id, Location.all, :id, :name, {}, { :multiple => false}  ) %>
<!--  </div>-->
<hr>
  <div class="field">
    <%= form.label :Item_Weight_In_Gram, class:'control-label' %>
    <input type="text" class="form-control" id="mission_weight" placeholder="Item weight in gram" name="mission[weight]">
    <%#= form.label :weight %>
    <%#= form.text_field :weight %>
  </div>

  <%= form.hidden_field :drone_id %>

  <!--  <div class="field">-->
  <%#= form.label :drone_id %>
  <%#= form.text_field :drone_id %>
  <!--  </div>-->
    <br>
    <button type="submit" class="btn btn-default">Submit</button>
<!--  <div class="actions">-->
    <%#= form.submit %>
<!--  </div>-->
<% end %>


</div>

app/views/drone/index.html.erb
<!DOCTYPE html>
<html>
<title>Index</title>
<body>

<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="jumbotron text-center">
  <h1>Problem Set 5</h1>
</div>



</body>

<!--    <h1>Problem Set 1</h1>-->

<hr>

<% if user_signed_in? %>
  <div class="container">
    <a href="drone/drone_registration" class="btn btn-primary" role="button">Drone Registration</a>
  </div>

  <hr>

  <div class="container">
    <a href="drone/drone_list" class="btn btn-primary" role="button">Drone List</a>
  </div>
<% else %>
  <div class="container">
    Please sign in to access drone registration
  </div>
  <hr>
<% end %>

app/views/drone/users_list.html.erb
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<!--<div class="container"><p class="text-success" id="notice"><%#= notice %></p>-->
<!--</div>-->

<div class="container">
  <h1>User Management</h1>
</div>

<div class="container">
  <table class="table">
    <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th>Registration Date</th>
      <th>Status</th>
      <th>Actions</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.in_time_zone("Asia/Bangkok") %></td>
        <% if user.banned %>
          <td>
            <p>Banned<span class="glyphicon glyphicon-remove" style="color: red"></span></p>
          </td>
          <td><%= link_to 'Unban', drone_ban_user_path(:id => user.id, :banned => false), method: :put %></td>
        <% else %>
          <td>
            <span class="glyphicon glyphicon-ok" style="color: green"></span>
          </td>
          <td><%= link_to 'Ban', drone_ban_user_path(:id => user.id, :banned => true), method: :put %></td>
          <td><%= link_to 'Show Missions', drone_users_mission_path(:id => user.id) %></td>
        <% end %>
        <!--        <td>-->
        <%# if user.banned %>
        <!--            <p>Banned<span class="glyphicon glyphicon-remove" style="color: red"></span></p>-->
        <%# else %>
        <!--            <span class="glyphicon glyphicon-ok" style="color: green"></span>-->
        <%# end %>
        <!--        </td>-->

        <!--        <td><%#= drone.status %></td>-->
        <!--        <td><%#= link_to 'Show', drone %></td>-->
        <!--      <td><%#= link_to 'Edit', edit_drone_path(drone) %></td>-->
        <!--      <td><%#= link_to 'Destroy', drone, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<!--<br>-->

<%#= link_to 'New Drone', new_drone_path %>

app/views/drone/users_mission.html.erb
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

</head>

<!--<style>-->
<!--  body {-->
<!--    background: #BFFFFE;-->
<!--    background: linear-gradient(to right, #BFFFFE, #BFFFFE);-->
<!--  }-->
<!--</style>-->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">DroneTracker</a>
    </div>
    <ul class="nav navbar-nav ">
      <div class="container">
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Drone
          </button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="/drone/drone_list">Drone List</a>
            <a class="dropdown-item" href="/drone/drone_registration">Register a Drone</a>
          </div>
        </div>
        <a href="/missions" class="btn btn-primary" role="button">Mission List</a>
        <a href="/" class="btn btn-info" role="button">Home</a>
        <a href="https://validator.w3.org" class="btn btn-info" role="button">Validate this Site</a>
        <a href="/posts" class="btn btn-info" role="button">Forum</a>
        <% if user_signed_in? %>
          <% if current_user.admin %>
            <a href="/drone/users_list" class="btn btn-info" role="button">User Management</a>
          <% end %>

          </div>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <div class="container">



              <li><p class="navbar-text">Signed in as <%= current_user.email %></p></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <% end %>

        </div>
        </ul>
        </div>
</nav>
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Missions</h1>
</div>

<div class="container">
  <div class="form-incline mt-2 mt-md-0">
    <%= form_tag search_missions_path, method: :get do %>
      <%= text_field_tag :search, nil, placeholder: "Search by Mission Name", class: "form-control mr-sm-2" %>
      <br>
      <%= submit_tag "Search", class: "btn btn-light my-2 my-sm-0" %>
    <% end %>
  </div>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Weight</th>
      <th>Drone</th>

      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @missions.each do |mission| %>
      <tr>
        <td><%= mission.name %></td>
        <td><%= mission.location.name %></td>
        <td><%= mission.weight %></td>
        <td><%= mission.drone.id %></td>


            </tr>

    <% end %>
    </tbody>
  </table>

  <%= link_to 'Drone List', drone_drone_list_path %>
</div>
<br>