config/routes.rb
Rails.application.routes.draw do
  resources :uptimes
  get 'mission_records/index'
  get 'polygon/polygon'
  get 'welcome/index'
  get 'forecasts/show'
  get 'forecasts/details'
  get 'forecasts/http'
  get 'drone/weather_check' => "drone#weather_check"
  put 'base/open_door'
  put 'base/close_door'

  resources :missions do
    collection do
      get :search
    end
  end
  resources :locations
  resources :comments
  resources :posts
  resources :nav_logs


  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :nav_logs
      get 'last_navlog', to: '/api/v1/nav_logs#last_navlog'
      resources :users
      resources :drone
      patch 'mission_status_change', to: 'drone#mission_status_change'
      patch 'terminate_mission', to: 'drone#terminate_mission'
      resources :missions
      get 'users_mission', to: 'missions#users_mission'
      get 'users_mission_last', to: 'missions#users_mission_last'
      get 'ongoing_mission', to: 'missions#ongoing_mission'
      post 'emergency_mission_sim', to: 'drone#emergency_mission_sim'
      post 'execute_emergency_mission', to: 'drone#execute_emergency_mission'

      resources :drone_availables
      post 'available', to: 'drone_availables#available'
    end
  end

  post 'polygon/send_coordinates' => 'polygon#get_coordinates'

  post '/auth/login', to: 'api/v1/authentication#login'



  get 'index/index'
  get 'index/about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/drone" => 'drone#index'
  get 'drone/drone_registration'
  get 'drone/drone_list' => "drone#drone_list"
  get 'drone/users_list'
  get 'drone/users_mission'
  get 'drone/drone_tracker'
  get 'drone/drone_mission'

  get 'drone/done'
  # get 'drone/drone_tracker' => 'drone#check_status'
  put 'drone/status_change'

  get 'drone/drone_tracker' => 'drone#check_status'
  put 'drone/terminate_mission'
  get 'drone/release_servo'
  get 'drone/lock_servo'

  put 'drone/mission_status_change'
  put 'drone/check_status'
  get 'drone/check_status'
  get '/drone/nav_logs_json' => 'drone#nav_logs_json'
  post 'drone/drone_create'
  put 'drone/ban_user'
  get 'drone/:id/drone_edit' => 'drone#drone_edit', :as => :drone_drone_edit

  patch 'drone/:id/drone_edit' => 'drone#drone_update'
  put 'drone/:id'=> 'drone#drone_update'

  devise_scope :user do
    authenticated :user do
      root to: 'index#index'
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end

  end

  # root 'index#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/drone.rb
class Drone < ApplicationRecord
  belongs_to :user
  has_many :nav_logs
  has_many :missions

end

app/models/drone_available.rb
class DroneAvailable < ApplicationRecord

end

app/models/forecast.rb
class Forecast < ApplicationRecord

  def get_weather_data
    ForecastIO.forecast(14.0754804, 100.6100677, params: { exclude: 'minutely, hourly'})
  end

end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :drone
  belongs_to :location
  belongs_to :user
  has_many :uptimes
  after_update :save_endtime

  def save_endtime

      @finduptime = Uptime.last
      @finduptime.end_time = Time.now
      @finduptime.save

  end

  def self.search(params)
    missions = Mission.where("Location LIKE ? or Name LIKE ?", "%{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
    missions
  end



end

app/models/nav_log.rb
class NavLog < ApplicationRecord
  belongs_to :drone
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/status_log.rb
class StatusLog < ApplicationRecord
  belongs_to :drone
end

app/models/uptime.rb
class Uptime < ApplicationRecord
  belongs_to :mission


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  has_many :missions

end

app/controllers/uptimes_controller.rb
class UptimesController < ApplicationController
  before_action :set_uptime, only: [:show, :edit, :update, :destroy]

  # GET /uptimes
  # GET /uptimes.json
  def index
    @uptimes = Uptime.all
  end

  # GET /uptimes/1
  # GET /uptimes/1.json
  def show
  end

  # GET /uptimes/new
  def new
    @uptime = Uptime.new
  end

  # GET /uptimes/1/edit
  def edit
  end

  # POST /uptimes
  # POST /uptimes.json
  def create
    @uptime = Uptime.new(uptime_params)

    respond_to do |format|
      if @uptime.save
        format.html { redirect_to @uptime, notice: 'Uptime was successfully created.' }
        format.json { render :show, status: :created, location: @uptime }
      else
        format.html { render :new }
        format.json { render json: @uptime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uptimes/1
  # PATCH/PUT /uptimes/1.json
  def update
    respond_to do |format|
      if @uptime.update(uptime_params)
        format.html { redirect_to @uptime, notice: 'Uptime was successfully updated.' }
        format.json { render :show, status: :ok, location: @uptime }
      else
        format.html { render :edit }
        format.json { render json: @uptime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uptimes/1
  # DELETE /uptimes/1.json
  def destroy
    @uptime.destroy
    respond_to do |format|
      format.html { redirect_to uptimes_url, notice: 'Uptime was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uptime
      @uptime = Uptime.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uptime_params
      params.require(:uptime).permit(:start_time, :end_time, :mission_id)
    end
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/drone_helper.rb
module DroneHelper
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/polygon_helper.rb
module PolygonHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/uptimes_helper.rb
module UptimesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/uptimes/_form.html.erb
<%= form_with(model: uptime, local: true) do |form| %>
  <% if uptime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(uptime.errors.count, "error") %> prohibited this uptime from being saved:</h2>

      <ul>
      <% uptime.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= form.label :mission_id %>
    <%= form.text_field :mission_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/uptimes/edit.html.erb
<h1>Editing Uptime</h1>

<%= render 'form', uptime: @uptime %>

<%= link_to 'Show', @uptime %> |
<%= link_to 'Back', uptimes_path %>

app/views/uptimes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Uptimes</h1>

<table>
  <thead>
    <tr>
      <th>Start time</th>
      <th>End time</th>
      <th>Mission</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uptimes.each do |uptime| %>
      <tr>
        <td><%= uptime.start_time %></td>
        <td><%= uptime.end_time %></td>
        <td><%= uptime.mission %></td>
        <td><%= link_to 'Show', uptime %></td>
        <td><%= link_to 'Edit', edit_uptime_path(uptime) %></td>
        <td><%= link_to 'Destroy', uptime, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Uptime', new_uptime_path %>

app/views/uptimes/new.html.erb
<h1>New Uptime</h1>

<%= render 'form', uptime: @uptime %>

<%= link_to 'Back', uptimes_path %>

app/views/uptimes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start time:</strong>
  <%= @uptime.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @uptime.end_time %>
</p>

<p>
  <strong>Mission:</strong>
  <%= @uptime.mission %>
</p>

<%= link_to 'Edit', edit_uptime_path(@uptime) %> |
<%= link_to 'Back', uptimes_path %>