config/routes.rb
Rails.application.routes.draw do
  resources :uptimes
  get 'mission_records/index'
  get 'polygon/polygon'
  get 'welcome/index'
  get 'forecasts/show'
  get 'forecasts/details'
  get 'forecasts/http'
  get 'drone/weather_check' => "drone#weather_check"
  put 'base/open_door'
  put 'base/close_door'

  resources :missions do
    collection do
      get :search
    end
  end
  resources :locations
  resources :comments
  resources :posts
  resources :nav_logs


  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :nav_logs
      get 'last_navlog', to: '/api/v1/nav_logs#last_navlog'
      resources :users
      resources :drone
      patch 'mission_status_change', to: 'drone#mission_status_change'
      patch 'terminate_mission', to: 'drone#terminate_mission'
      resources :missions
      get 'users_mission', to: 'missions#users_mission'
      get 'users_mission_last', to: 'missions#users_mission_last'
      get 'ongoing_mission', to: 'missions#ongoing_mission'
      post 'emergency_mission_sim', to: 'drone#emergency_mission_sim'
      post 'execute_emergency_mission', to: 'drone#execute_emergency_mission'

      resources :drone_availables
      post 'available', to: 'drone_availables#available'
    end
  end

  post 'polygon/send_coordinates' => 'polygon#get_coordinates'

  post '/auth/login', to: 'api/v1/authentication#login'



  get 'index/index'
  get 'index/about'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/drone" => 'drone#index'
  get 'drone/drone_registration'
  get 'drone/drone_list' => "drone#drone_list"
  get 'drone/users_list'
  get 'drone/users_mission'
  get 'drone/drone_tracker'
  get 'drone/drone_mission'

  get 'drone/done'
  # get 'drone/drone_tracker' => 'drone#check_status'
  put 'drone/status_change'

  get 'drone/drone_tracker' => 'drone#check_status'
  put 'drone/terminate_mission'
  get 'drone/release_servo'
  get 'drone/lock_servo'

  put 'drone/mission_status_change'
  put 'drone/check_status'
  get 'drone/check_status'
  get '/drone/nav_logs_json' => 'drone#nav_logs_json'
  post 'drone/drone_create'
  put 'drone/ban_user'
  get 'drone/:id/drone_edit' => 'drone#drone_edit', :as => :drone_drone_edit

  patch 'drone/:id/drone_edit' => 'drone#drone_update'
  put 'drone/:id'=> 'drone#drone_update'

  devise_scope :user do
    authenticated :user do
      root to: 'index#index'
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end

  end

  # root 'index#index'
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :drone
  belongs_to :location
  belongs_to :user
  has_many :uptimes
  after_update :save_endtime

  def save_endtime

      @finduptime = Uptime.last
      @finduptime.end_time = Time.now
      @finduptime.save

  end

  def self.search(params)
    missions = Mission.where("Location LIKE ? or Name LIKE ?", "%{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
    missions
  end



end

app/controllers/api/v1/missions_controller.rb
module Api
  module V1
    class MissionsController < ApplicationController
      # TODO
      before_action :authorize_request, except: [:create, :update]
      protect_from_forgery with: :null_session
      respond_to :json
      def index
        respond_with Mission.all
      end

      def ongoing_mission
        @user = User.find(params[:id])
        @missions = Mission.where(:status => "Ongoing")
        respond_with @missions
      end

      def users_mission
        @user = User.find(params[:id])
        @missions = Mission.where(:user => @user)
        respond_with @missions
      end

      def users_mission_last
        @user = User.find(params[:id])
        @missions = Mission.where(:user => @user)
        respond_with @missions.last
      end

      def create
        @mission = Mission.new(mission_params)
        @mission.mission_type = "Delivery"
        if @mission.save
          render json: @mission, status: :created
        else
          render json: { errors: @mission.errors.full_messages },
                 status: :unprocessable_entity
        end
      end

      def update
        @mission = Mission.find(params[:id])
        @mission.update(mission_params)
      end

      def mission_params
        params.permit(:status, :name, :location_id, :weight, :drone_id, :user_id)
      end
    end
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :set_mission, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index]
  # GET /missions
  # GET /missions.json
  def index
    @missions = Mission.order("drone_id")
    user = current_user
    if user.admin
      @missions = Mission.all
    else
      @missions = Mission.where(:user => user)
    end

  end

  # GET /missions/1
  # GET /missions/1.json
  def show
  end

  # GET /missions/new
  def new
    @mission = Mission.new
  end

  # GET /missions/1/edit
  def edit
  end

  def endtime

  end

  def search
    if params[:search].blank?
      @missions = Mission.all
    else
      @missions = Mission.search(params)
    end
  end

  # POST /missions
  # POST /missions.json
  def create
    @mission = Mission.new(mission_params.merge(user_id: current_user.id))
    @mission.status = "Saved"
    @mission.mission_type = "Delivery"

    respond_to do |format|
      if @mission.save
        format.html { redirect_to missions_path, notice: 'Mission was successfully created.' }
        format.json { render :show, status: :created, location: @mission }
      else
        format.html { render :new }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  def status_change
    @drone = Drone.find(params[:id])
    @drone.status = params[:status]

    mis_status = StatusLog.new
    mis_status.mission = @drone
    mis_status.status = @drone.status
    mis_status.save

    respond_to do |format|
      if @drone.update(drone_params)
        format.html { redirect_to missions_path, notice: 'Mission status has been updated.' }
        format.json { render :show, status: :ok, location: @drone}
      else
        format.html { render :edit }
        format.json { render json: @drone.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /missions/1
  # PATCH/PUT /missions/1.json
  def update
    respond_to do |format|
      if @mission.update(mission_params)
        format.html { redirect_to @mission, notice: 'Mission was successfully updated.' }
        format.json { render :show, status: :ok, location: @mission }
      else
        format.html { render :edit }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  rescue ActiveRecord::StaleObjectError
    render :conflict
  end

  # DELETE /missions/1
  # DELETE /missions/1.json
  def destroy
    if current_user.admin
      @users = User.all

    @mission.destroy
    respond_to do |format|
      format.html { redirect_to missions_path, notice: 'Mission was successfully destroyed.' }
      format.json { head :no_content }
    end

    else
      redirect_to missions_path, alert: "You need admin privileges."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mission
      @mission = Mission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mission_params
      params.require(:mission).permit(:name, :location_id, :weight, :drone_id, :status, :mission_id, :user_id, :lock_version)
    end
end

def drone_params
  params.permit(:name, :status)
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/views/missions/_form.html.erb
<%= form_with(model: mission, local: true) do |form| %>
  <% if mission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mission.errors.count, "error") %> prohibited this mission from being saved:</h2>

      <ul>
      <% mission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item_name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= collection_select( :mission, :location_id, Location.all, :id, :name, {}, { :multiple => false} ) %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.text_field :weight %>
  </div>

  <%= form.hidden_field :drone_id %>
  <%= form.hidden_field :user_id %>
  <%= form.hidden_field :lock_version %>
  <%= form.hidden_field :status %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>




</body>
</html>

app/views/missions/edit.html.erb
<h1>Editing Mission</h1>

<%= render 'form', mission: @mission %>

<%= link_to 'Show', @mission %> |
<%= link_to 'Back', missions_path %>

app/views/missions/index.html.erb
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

</head>
<style>
  .open_close {
    margin-bottom: 10px;
  }
</style>
<!--<style>-->
<!--  body {-->
<!--    background: #BFFFFE;-->
<!--    background: linear-gradient(to right, #BFFFFE, #BFFFFE);-->
<!--  }-->
<!--</style>-->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">DroneTracker</a>
    </div>
    <ul class="nav navbar-nav ">
      <div class="container">
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Drone
          </button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="/drone/drone_list">Drone List</a>
            <a class="dropdown-item" href="/drone/drone_registration">Register a Drone</a>
          </div>
        </div>
        <a href="/missions" class="btn btn-primary" role="button">Mission List</a>
        <a href="/" class="btn btn-info" role="button">Home</a>
        <a href="https://validator.w3.org" class="btn btn-info" role="button">Validate this Site</a>
        <a href="/posts" class="btn btn-info" role="button">Forum</a>
        <% if user_signed_in? %>
          <% if current_user.admin %>
            <a href="/drone/users_list" class="btn btn-info" role="button">User Management</a>
          <% end %>

          </div>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <div class="container">



              <li><p class="navbar-text">Signed in as <%= current_user.email %></p></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <% end %>

        </div>
        </ul>
  </div>
</nav>
<p id="notice"><%= notice %></p>

<div class="container">
<h1>Missions</h1>
</div>

<div class="container">
  <div class="form-incline mt-2 mt-md-0">
  <%= form_tag search_missions_path, method: :get do %>
    <%= text_field_tag :search, nil, placeholder: "Search by Mission Name", class: "form-control mr-sm-2" %>
      <br>
    <%= submit_tag "Search", class: "btn btn-light my-2 my-sm-0" %>
    <% end %>
  </div>
  <div class="open_close">
      <span class="open_door"> <%= link_to 'Open Door', base_open_door_path, method: :put %> </span>
      <span class="close_door"> <%= link_to 'Close Door', base_close_door_path, method: :put %> </span>
    </div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Mission Created Date</th>
      <th>Name</th>
      <th>Location</th>
      <th>Weight</th>
      <th>Drone</th>
      <th>Status</th>
      <th>Uptime</th>
      <th>Last Start Time</th>
      <th>Last End Time</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @missions.each do |mission| %>
      <tr>
        <td><%= mission.created_at.in_time_zone('Asia/Bangkok')  %></td>
        <td><%= mission.name %></td>
        <td><%= mission.location.name %></td>
        <td><%= mission.weight %></td>
        <td><%= mission.drone.id %></td>
        <td><%= mission.status %></td>
       <td>
         <% if mission.status == 'Ongoing' %>
         <% a = Time.now - mission.updated_at.in_time_zone('Asia/Bangkok') %>
         <%= Time.at(a).utc.strftime("%H:%M:%S")%>
         <%end %>
       </td>
        <td>
          <%# if mission.status == 'Ongoing' %>
          <%# a = Time.now - mission.updated_at.in_time_zone('Asia/Bangkok') %>
           <%#= Time.at(a).utc.strftime("%H:%M:%S")%>
          <%#end %>
            <%if mission.uptimes.last.blank? %>
            "Not Available"
            <% else %>
          <% a = mission.uptimes.last.start_time %>
            <%= a.strftime("%H:%M:%S") %>
            <% end %>
        </td>



        <td>
          <%if mission.uptimes.last.blank? %>
            "Not Available"
          <% else %>
            <%= mission.uptimes.last.end_time %>

          <% end %>
        </td>

          <td>
            <% if mission.drone.status == 'Busy' %>
          "Drone is currently on a mission"
          <% else %>
         <%= link_to 'Execute Mission', drone_mission_status_change_path(:id => mission.id, :mission_status => "Ongoing", :drone_status => "Busy"), method: :put  %>
            </td>
        <%end %>


          <td> <% if mission.status == "Ongoing" %>
              <%= link_to "tracking", drone_drone_tracker_path(drone: mission.drone.id) %>
            <%end %>
          </td>

          <td><% if mission.status == "Ongoing" %>
            <%= link_to "Terminate", drone_terminate_mission_path(:id => mission.id, :drone => mission.drone.id, :drone_status => "Available", :mission_status => "Done"), method: :put, data: { confirm: 'Are you sure?' }%></td>
              <%end %>
            <td><%= link_to 'Destroy', mission, class: "btn btn-danger",method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>


    <% end %>
  </tbody>
</table>

  <%= link_to 'Drone List', drone_drone_list_path %>
</div>
<br>

app/views/missions/new.html.erb
<h1>New Mission</h1>

<%= render 'form', mission: @mission %>

<%= link_to 'Back', missions_path %>

app/views/missions/search.html.erb
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

</head>

<!--<style>-->
<!--  body {-->
<!--    background: #BFFFFE;-->
<!--    background: linear-gradient(to right, #BFFFFE, #BFFFFE);-->
<!--  }-->
<!--</style>-->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">DroneTracker</a>
    </div>
    <ul class="nav navbar-nav ">
      <div class="container">
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Drone
          </button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="/drone/drone_list">Drone List</a>
            <a class="dropdown-item" href="/drone/drone_registration">Register a Drone</a>
          </div>
        </div>
        <a href="/missions" class="btn btn-primary" role="button">Mission List</a>
        <a href="/" class="btn btn-info" role="button">Home</a>
        <a href="https://validator.w3.org" class="btn btn-info" role="button">Validate this Site</a>
        <a href="/posts" class="btn btn-info" role="button">Forum</a>
        <% if user_signed_in? %>
          <% if current_user.admin %>
            <a href="/drone/users_lists" class="btn btn-info" role="button">User Management</a>
          <% end %>

          </div>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <div class="container">



              <li><p class="navbar-text">Signed in as <%= current_user.email %></p></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><a href="/users/sign_up"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="/users/sign_in"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <% end %>

        </div>
        </ul>
        </div>
</nav>
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>Missions</h1>
</div>




<div class="container">
  <div class="form-incline mt-2 mt-md-0">
    <%= form_tag search_missions_path, method: :get do %>
      <%= text_field_tag :search, nil, placeholder: "search", class: "form-control mr-sm-2" %>
      <br>
      <%= submit_tag "Search", class: "btn btn-light my-2 my-sm-0" %>
    <% end %>
  </div>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Weight</th>
      <th>Drone</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @missions.each do |mission| %>
      <tr>
        <td><%= mission.name %></td>
        <td><%= mission.location.name %></td>
        <td><%= mission.weight %></td>
        <td><%= mission.drone.id %></td>
        <td><%= mission.status %></td>
        <%# if mission.status == 'Saved'  %>
        <!--          <td><%#= link_to 'Execute Mission', drone_mission_status_change_path(:id => mission.id, :mission_status => "Ongoing", :drone_status => "Busy"), method: :put  %>-->

        <!--        </td>-->
        <%#end %>
        <td>
          <% if mission.drone.status == 'Busy'  %>
            "Drone is currently on a mission"
          <% else %>
            <%= link_to 'Execute Mission', drone_mission_status_change_path(:id => mission.id, :mission_status => "Ongoing", :drone_status => "Busy"), method: :put  %>

            </td>
          <%end %>

          <td> <% if mission.status == "Ongoing" %>
              <%= link_to "done", drone_mission_status_change_path(:id => mission.id, :drone_status => "Available", :mission_status => "done" ), method: :put %>
            <%end %>
          </td>



          </tr>
    <% end %>
    </tbody>
  </table>

  <%= link_to 'Drone List', drone_drone_list_path %>
</div>
<br>

app/views/missions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mission.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @mission.location %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @mission.weight %>
</p>

<p>
  <strong>Drone:</strong>
  <%= @mission.drone.id %>
</p>

<%= link_to 'Edit', edit_mission_path(@mission) %> |
<%= link_to 'Back', missions_path %>